// Rebuild both coordinate projections and the browser bundle from one source.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const cp = require('node:child_process');
const gcoord = require('./assets/vendor/gcoord-1.0.7.cjs');
const root = __dirname;
const filename = path.join(root, 'assets/property-locations.json');
const data = JSON.parse(fs.readFileSync(filename, 'utf8'));
for (const entry of Object.values(data.properties)) {
  for (const [key, crs] of [['wgs84', 'WGS84'], ['gcj02', 'GCJ02']]) {
    if (!entry.sourcePoint) {
      entry[key] = null;
      continue;
    }
    const p = entry.sourcePoint;
    const [lng, lat] = gcoord.transform([p.lng, p.lat], gcoord[p.crs], gcoord[crs]);
    entry[key] = {lat: Number(lat.toFixed(8)), lng: Number(lng.toFixed(8))};
  }
}
fs.writeFileSync(filename, JSON.stringify(data, null, 2) + '\n');
fs.writeFileSync(path.join(root, 'assets/property-locations.js'),
  '// Generated by update_locations.cjs. Edit property-locations.json instead.\n' +
  'window.HOUSE_LOCATIONS = ' + JSON.stringify(data).replace(/</g, '\\u003c') + ';\n');

const out = path.join(root, 'exports/location-audit');
const comparisonPath = path.join(out, 'location-comparison.json');
let originals;
if (fs.existsSync(comparisonPath)) {
  originals = Object.fromEntries(JSON.parse(fs.readFileSync(comparisonPath, 'utf8'))
    .map(entry => [entry.key, entry.originalWebsite]));
} else {
  const oldHtml = cp.execFileSync('git', ['show', 'HEAD:index.html'], {cwd: root, encoding: 'utf8'});
  const oldItems = vm.runInNewContext(oldHtml.match(/const items=(\[[\s\S]*?\]);/)[1]);
  originals = Object.fromEntries(oldItems.map((entry, index) => [`project-${index}`, entry]));
}
const distance = (a, b) => {
  const r = Math.PI / 180;
  const x = Math.sin((b.lat-a.lat)*r/2)**2 + Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lng-a.lng)*r/2)**2;
  return 6371 * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1-x));
};
const report = ['# 西安候选楼盘位置核查 2026年9月24日', '',
  '范围：网站全部30个候选项目。25项取得小区、入口或期内楼栋参考点；5项仍不能给出可靠唯一坐标。地图定位不是逐套房源核验，也不代表已实地踏勘。', '',
  '网站原坐标没有来源与坐标系记录；表内位移按原网站实际使用的WGS84绘制口径比较，仅用于衡量旧点误差。', '',
  '网站继续使用OSM/WGS84，文档使用高德/GCJ02。两处从同一份数据转换，不能直接比较两个坐标系的数值是否相等。', '',
  '原文档中德通昆仑序、金辉天鹅湾使用的估算点已撤下。待核项目不使用旧坐标回退。华润三期、蓝光二期、融创二期及花千树的期数仍须核对。', '',
  '|项目|状态|核对地址|距旧网站点约km|证据及限制|', '|---|---|---|---:|---|'];
const changes = [];
for (const [key, entry] of Object.entries(data.properties)) {
  const original = originals[key] || {};
  const km = entry.wgs84 && Number.isFinite(original.lat) && Number.isFinite(original.lng)
    ? distance(original, entry.wgs84) : null;
  changes.push({key, name: entry.name, originalWebsite: {lat: original.lat, lng: original.lng}, ...entry, displacementKm: km});
  report.push(`|${entry.name}|${entry.statusLabel}|${entry.address}|${km === null ? '未确定' : km.toFixed(2)}|${entry.note} [来源](${entry.sources[0]})|`);
}
fs.mkdirSync(out, {recursive: true});
fs.writeFileSync(path.join(out, '楼盘位置核查报告.md'), report.join('\n') + '\n');
fs.writeFileSync(path.join(out, 'location-comparison.json'), JSON.stringify(changes, null, 2) + '\n');
console.log(`Rebuilt ${Object.keys(data.properties).length} locations; ${changes.filter(x=>x.wgs84).length} mapped.`);
